<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Newtonsoft.Json support for TcfOss.Filtering.Contracts filter polymorphism.</Description>
    <PackageTags>filtering;contracts;json;newtonsoft;serialization</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="[13.0.4,14)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TcfOss.Filtering.Contracts\TcfOss.Filtering.Contracts.csproj" />
  </ItemGroup>

</Project>
